class Flags
{
  constructor()
  {
    this.FLAG_NULL = 0;
    this.FLAG_REPRESENTATION_STRING_BSTR = 1;
    this.FLAG_REPRESENTATION_STRING_LPCTSTR = 2;
    this.FLAG_REPRESENTATION_STRING_LPWSTR = 4;
    this.FLAG_REPRESENTATION_ARRAY = 8;
    this.FLAG_REPRESENTATION_POINTER = 16;
    this.FLAG_REPRESENTATION_REFERENCE = 32;
    this.FLAG_REPRESENTATION_DISPATCH_INVOKE = 64;
    this.FLAG_REPRESENTATION_NESTED_POINTER = 128;
    this.FLAG_REPRESENTATION_UNSIGNED_BYE = 256;
    this.FLAG_REPRESENTATION_UNSIGNED_SHORT = 512;
    this.FLAG_REPRESENTATION_UNSIGNED_INT = 1024;
    this.FLAG_REPRESENTATION_VT_INT = 2048;
    this.FLAG_REPRESENTATION_VT_UINT = 4096;
    this.FLAG_REPRESENTATION_VARIANT_BOOL = 8192;
    this.FLAG_REPRESENTATION_VALID_STRING = 16384;
    this.FLAG_REPRESENTATION_INTERFACEPTR_DECODE2 = 32768;
    this.FLAG_REPRESENTATION_UNKNOWN_IID = 65536;
    this.FLAG_REPRESENTATION_USE_DISPATCH_IID = 131072;
    this.FLAG_REPRESENTATION_UNKNOWN_NULL_FOR_OUT = 262144;
    this.FLAG_REPRESENTATION_DISPATCH_NULL_FOR_OUT = 524288;
    this.FLAG_REPRESENTATION_SET_INTERFACEPTR_NULL_FOR_VARIANT = 1048576;
  }
}

module.exports = Flags;
