//@ts-check

module.exports = {
  FLAG_NULL: 0,
  FLAG_REPRESENTATION_STRING_BSTR: 1,
  FLAG_REPRESENTATION_STRING_LPCTSTR: 2,
  FLAG_REPRESENTATION_STRING_LPWSTR: 4,
  FLAG_REPRESENTATION_ARRAY: 8,
  FLAG_REPRESENTATION_POINTER: 16,
  FLAG_REPRESENTATION_REFERENCE: 32,
  FLAG_REPRESENTATION_DISPATCH_INVOKE: 64,
  FLAG_REPRESENTATION_NESTED_POINTER: 128,
  FLAG_REPRESENTATION_UNSIGNED_BYE: 256,
  FLAG_REPRESENTATION_UNSIGNED_SHORT: 512,
  FLAG_REPRESENTATION_UNSIGNED_INT: 1024,
  FLAG_REPRESENTATION_VT_INT: 2048,
  FLAG_REPRESENTATION_VT_UINT: 4096,
  FLAG_REPRESENTATION_VARIANT_BOOL: 8192,
  FLAG_REPRESENTATION_VALID_STRING: 16384,
  FLAG_REPRESENTATION_INTERFACEPTR_DECODE2: 32768,
  FLAG_REPRESENTATION_UNKNOWN_IID: 65536,
  FLAG_REPRESENTATION_USE_DISPATCH_IID: 131072,
  FLAG_REPRESENTATION_UNKNOWN_NULL_FOR_OUT: 262144,
  FLAG_REPRESENTATION_DISPATCH_NULL_FOR_OUT: 524288,
  FLAG_REPRESENTATION_SET_INTERFACEPTR_NULL_FOR_VARIANT: 1048576
};
